### ISSUE TITLE
why restrict to only ImageProvider<Object>? 

### ISSUE THREAD

**Issue by ShankarKakumani** [Prayag-X/parallax_sensors_bg#11]
-> you can change it to a widget and let us pass any widget into the Layer.

**Comment by Prayag-X** [comment]
yes @ShankarKakumani you can pass any widget into the layer as ```child```.  See the example I have mentioned in the readme.

```dart
...
Layer(
    sensitivity: yourSensitivity,
    child: AnyWidget(),
),
...
```

I just forgot to mention this '''child''' argument in the readme 🤦‍♂️. Thanks for the first issue 💕. I will mention it in the readme.

**Comment by ShankarKakumani** [comment]
Yeah, I did realise about this after I raised the issue. We can close this now

**Comment by Prayag-X** [comment]
Ok thanks.
